### ISSUE TITLE
[Script] Doom Naming Style Exporter

### ISSUE THREAD

**Issue by jvornhagen** [projectitis/aseprite-community-script-collection#2]
>If you are submitting multiple scripts, please submit each as a separate issue - even if they are all in the same repository.
> Please replace the placeholders with your own information and delete those that don't apply

## Short name of my script

DNS Exporter

## Short description of the script

This script allows to automatically export Aseprite files following the DOOM naming conventions. 
Eg: An image with 3 frames will be exported as POSSA0, POSSB0, POSSC0.
Allows to set sprite angles, mirroring, and custom export range and starting letter.

## Link to where the script can be found

https://github.com/jvornhagen/DoomStyleSpriteExporterForAseprite

## (Optional) Link to your preferred user profile

https://community.aseprite.org/u/thesartremaster

## (Optional) Link to the Aseprite forum post where you have posted your script

https://community.aseprite.org/t/doom-style-sprite-exporter/21240

**Comment by projectitis** [comment]
Thanks for the contribution!

**Comment by jvornhagen** [comment]
Thanks for setting this all up^^
Its super useful
