### ISSUE TITLE
Aseprite Lottie Export

### ISSUE THREAD

**Issue by behreajj** [projectitis/aseprite-community-script-collection#3]
## Short name of my script

Aseprite Lottie Export

## Short description of the script

Exports a sprite as a [lottie](https://lottiefiles.com/) file. Lotties are animated vector files. This makes a flattened composite of the sprite, then treats each pixel as a rectangle.

## Link to where the script can be found

https://github.com/behreajj/aselottieexport

## (Optional) Link to your preferred user profile

https://community.aseprite.org/u/behreandtjeremy/summary

**Comment by projectitis** [comment]
So sorry about the delay! Not sure how I missed it.
